// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = require('./lib/iOSAppBundleInfo');

  module.exports.ios = require('./lib/iOSAppBundleInfo');

  module.exports.android = require('./lib/AndroidAppBundleInfo');

}).call(this);
