// Generated by CoffeeScript 1.9.3
(function() {
  var AndroidBundleInfo, AppBundleInfo, iOSBundleInfo;

  module.exports = AppBundleInfo = require('./lib/iOSAppBundleInfo');

  module.exports.iOS = module.exports.ios = iOSBundleInfo = require('./lib/iOSAppBundleInfo');

  module.exports.Android = module.exports.android = AndroidBundleInfo = require('./lib/AndroidAppBundleInfo');

  module.exports.autodetect = function(fileOrStream, callback) {
    var abi;
    abi = new AppBundleInfo(fileOrStream);
    return abi.findFileStream(AndroidBundleInfo.prototype.manifestPath, function(err, manifest) {
      var bi;
      if (manifest) {
        bi = new AndroidBundleInfo(null);
        bi.extracted = true;
        bi.extractPath = abi.extractPath;
        return callback(null, bi);
      }
      return abi.findFileStream(iOSBundleInfo.prototype.plistPath, function(err, plist) {
        if (plist) {
          bi = new iOSBundleInfo(null);
          bi.extracted = true;
          bi.extractPath = abi.extractPath;
          return callback(null, bi);
        }
        return callback(new Error('could not recognize bundle'));
      });
    });
  };

}).call(this);
